soft_list = [
    {
        "Software title": "Firefox",
        "OS Available": ["Windows 7", "Windows 8", "Windows 10"],
        "Category": "Common",
        "Checkbox":"Yes",
        "32-bit link:":"https://download-installer.cdn.mozilla.net/pub/firefox/releases/114.0.1/win32/en-US/Firefox%20Setup%20114.0.1.msi" ,
        "64-bit link:":"https://download-installer.cdn.mozilla.net/pub/firefox/releases/114.0.1/win64/en-US/Firefox%20Setup%20114.0.1.msi" ,
        "Software_name:":"firefox.msi",
        "Software_type:":"msi",
    },
    {
        "Software title": "Steam",
        "OS Available": ["Windows 7", "Windows 8", "Windows 10"],
        "Category": "Gaming",
        "Checkbox":"Yes",
        "Generic link:":"https://cdn.akamai.steamstatic.com/client/installer/SteamSetup.exe",
        "Software_name:":"Steam.exe",
        "Software_type:":"exe",
    },
    {
        "Software title": "Have i been pwned",
        "OS Available": ["Windows 7", "Windows 8", "Windows 10"],
        "Category": "Tools",
        "Got_Window":"Yes",
        "Script":"hibp.py",
    },
    {
        "Software title": "Speed Test",
        "OS Available": ["Windows 7", "Windows 8", "Windows 10"],
        "Category": "Tools",
        "Got_Window":"Yes",
        "Script":"speedtest.py",
    },
    {
        "Software title": "PC Specs",
        "OS Available": ["Windows 7", "Windows 8", "Windows 10"],
        "Category": "Tools",
        "Got_Window":"Yes",
        "Script":"pc_specs.py",
    },
    {
        "Software title": "7Zip",
        "OS Available": ["Windows 7", "Windows 8", "Windows 10"],
        "Category": "Common",
        "Checkbox":"Yes",
        "Generic link:":"https://www.7-zip.org/a/7z2300-x64.msi",
        "Software_name:":"7zip.msi",
        "Software_type:":"msi",
    },
    {
        "Software title": "Chrome",
        "OS Available": ["Windows 7", "Windows 8", "Windows 10"],
        "Category": "Common",
        "Checkbox":"Yes",
        "Generic link:":"https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7B70950934-188A-387E-DDA2-7331602507D4%7D%26lang%3Den%26browser%3D3%26usagestats%3D0%26appname%3DGoogle%2520Chrome%26needsadmin%3Dtrue%26ap%3Dx64-stable-statsdef_0%26brand%3DGCEA/dl/chrome/install/googlechromestandaloneenterprise64.msi",
        "Software_name:":"Chrome.msi",
        "Software_type:":"msi",
    },
    {
        "Software title": "Anydesk",
        "OS Available": ["Windows 7", "Windows 8", "Windows 10"],
        "Category": "Remote Desktop",
        "Checkbox":"Yes",
        "Generic link:":"https://download.anydesk.com/AnyDesk.msi",
        "Software_name:":"Anydesk.msi",
        "Software_type:":"msi",
    },
    {
        "Software title": "VLC",
        "OS Available": ["Windows 7", "Windows 8", "Windows 10"],
        "Category": "Common",
        "Checkbox":"Yes",
        "Generic link:":"https://mirrors.neterra.net/vlc/vlc/3.0.8/win64/vlc-3.0.8-win64.msi",
        "Software_name:":"VLC.msi",
        "Software_type:":"msi",
    },    
    {
        "Software title": "Discord",
        "OS Available": ["Windows 7", "Windows 8", "Windows 10"],
        "Category": "Gaming",
        "Checkbox":"Yes",
        "Generic link:":"https://dl.discordapp.net/distro/app/stable/win/x86/1.0.9013/DiscordSetup.exe",
        "Software_name:":"Discord.exe",
        "Software_type:":"exe",
    },      
    {
        "Software title": "Winrar",
        "OS Available": ["Windows 7", "Windows 8", "Windows 10"],
        "Category": "Common",
        "Checkbox":"Yes",
        "32-bit link:":"https://www.win-rar.com/fileadmin/winrar-versions/winrar/winrar-x32-622.exe" ,
        "64-bit link:":"https://www.win-rar.com/fileadmin/winrar-versions/winrar/winrar-x64-622.exe" ,
        "Software_name:":"Winrar.exe",
        "Software_type:":"exe",
    },    
    {
        "Software title": "Wireshark",
        "OS Available": ["Windows 7", "Windows 8", "Windows 10"],
        "Category": "Network",
        "Checkbox":"Yes",
        "Generic link:":"https://2.na.dl.wireshark.org/win64/Wireshark-win64-4.0.6.exe",
        "Software_name:":"Wireshark.exe",
        "Software_type:":"exe",
    },  
    {
        "Software title": "Python",
        "OS Available": ["Windows 8", "Windows 10"],
        "Category": "Programming",
        "Checkbox":"Yes",
        "32-bit link:":"https://www.python.org/ftp/python/3.11.4/python-3.11.4.exe" ,
        "64-bit link:":"https://www.python.org/ftp/python/3.11.4/python-3.11.4-amd64.exe" ,
        "Software_name:":"Python.exe",
        "Software_type:":"exe",
    },    
    {
        "Software title": "Notepad ++",
        "OS Available": ["Windows XP","Windows 7","Windows 8", "Windows 10"],
        "Category": "Common",
        "Checkbox":"Yes",
        "32-bit link:":"https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8/npp.7.8.Installer.exe" ,
        "64-bit link:":"https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8/npp.7.8.Installer.x64.exe" ,
        "Software_name:":"notepadplusplus.exe",
        "Software_type:":"exe",
    },    
    {
        "Software title": "Advanced IP Scanner",
        "OS Available": ["Windows XP","Windows 7","Windows 8", "Windows 10"],
        "Category": "Network",
        "Checkbox":"Yes",
        "Generic link:":"https://download.advanced-ip-scanner.com/download/files/Advanced_IP_Scanner_2.5.4594.1.exe" ,
        "Software_name:":"advancedip.exe",
        "Software_type:":"exe",
        "Special_command_exists:":"Yes",
        "Special_Command:":"advancedip.exe /SILENT /NORESTART",

    },   
    {
        "Software title": "TeamViewer",
        "OS Available": ["Windows 8", "Windows 10"],
        "Category": "Remote Desktop",
        "Checkbox":"Yes",
        "32-bit link:":"https://dl.teamviewer.com/download/version_15x/TeamViewer_Setup.exe?ref=https%3A%2F%2Fwww.teamviewer.com%2Fen-us%2Fdownload%2Fwindows%2F" ,
        "64-bit link:":"https://dl.teamviewer.com/download/version_15x/TeamViewer_Setup_x64.exe?ref=https%3A%2F%2Fwww.teamviewer.com%2Fen-us%2Fdownload%2Fwindows%2F" ,
        "Software_name:":"teamviewer.exe",
        "Software_type:":"exe",
    },  
    
    {
        "Software title": "WinSCP",
        "OS Available": ["Windows 7","Windows 8", "Windows 10"],
        "Category": "Network",
        "Checkbox":"Yes",
        "Generic link:":"https://deac-ams.dl.sourceforge.net/project/winscp/WinSCP/6.1.1/WinSCP-6.1.1-Setup.exe" ,
        "Software_name:":"winscp.exe",
        "Software_type:":"exe",
        "Special_command_exists:":"Yes",
        "Special_Command:":"winscp.exe /SILENT /NORESTART /ALLUSERS",
    },  
    {
        "Software title": "Virtual Box",
        "OS Available": ["Windows 7","Windows 8", "Windows 10"],
        "Category": "IT",
        "Checkbox":"Yes",
        "Generic link:":"https://download.virtualbox.org/virtualbox/7.0.8/VirtualBox-7.0.8-156879-Win.exe" ,
        "Software_name:":"virtualbox.exe",
        "Software_type:":"exe",
        "Special_command_exists:":"Yes",
        "Special_Command:":"virtualbox.exe --silent --ignore-reboot",
        
    },  
    {
        "Software title": "Malwarebytes",
        "OS Available": ["Windows 7","Windows 8", "Windows 10"],
        "Category": "Anti-Virus",
        "Checkbox":"Yes",
        "Generic link:":"https://www.malwarebytes.com/api/downloads/mb-windows?filename=MBSetup.exe" ,
        "Software_name:":"malwarebytes.exe",
        "Software_type:":"exe",
        "Special_command_exists:":"Yes",
        "Special_Command:":"malwarebytes.exe /SILENT /NORESTART",
    },
    
    {
        "Software title": "OpenVPN",
        "OS Available": ["Windows 7", "Windows 8", "Windows 10"],
        "Category": "IT",
        "Checkbox":"Yes",
        "Generic link:":"https://swupdate.openvpn.net/downloads/connect/openvpn-connect-3.3.7.2979_signed.msi",
        "Software_name:":"openvpn.msi",
        "Software_type:":"msi",
    },
    
    {
        "Software title": "GIMP",
        "OS Available": ["Windows 7","Windows 8", "Windows 10"],
        "Category": "Design",
        "Checkbox":"Yes",
        "Generic link:":"https://ftp.cc.uoc.gr/mirrors/gimp/pub/gimp/v2.10/windows/gimp-2.10.34-setup.exe" ,
        "Software_name:":"gimp.exe",
        "Software_type:":"exe",
        "Special_command_exists:":"Yes",
        "Special_Command:":"gimp.exe /SILENT /NORESTART /ALLUSERS",
    },
    {
        "Software title": "KeePass",
        "OS Available": ["Windows 7","Windows 8", "Windows 10"],
        "Category": "IT",
        "Checkbox":"Yes",
        "Generic link:":"https://nav.dl.sourceforge.net/project/keepass/KeePass%202.x/2.54/KeePass-2.54-Setup.exe" ,
        "Software_name:":"keepass.exe",
        "Software_type:":"exe",
        "Special_command_exists:":"Yes",
        "Special_Command:":"keepass.exe /SILENT /NORESTART",
    },
    {
        "Software title": "Adobe PDF Reader",
        "OS Available": ["Windows 7","Windows 8", "Windows 10"],
        "Category": "Common",
        "Checkbox":"Yes",
        "Generic link:":"https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/2300320215/AcroRdrDC2300320215_en_US.exe" ,
        "Software_name:":"adobepdf.exe",
        "Software_type:":"exe",
        "Special_command_exists:":"Yes",
        "Special_Command:":"adobepdf.exe /sAll /rs /msi EULA_ACCEPT=YES",
    },
    {
        "Software title": "CPU-Z",
        "OS Available": ["Windows 7","Windows 8", "Windows 10"],
        "Category": "PC Check",
        "Checkbox":"Yes",
        "Generic link:":"https://download.cpuid.com/cpu-z/cpu-z_2.06-en.exe" ,
        "Software_name:":"cpuz.exe",
        "Software_type:":"exe",
        "Special_command_exists:":"Yes",
        "Special_Command:":"cpuz.exe /SILENT /NORESTART",
    },
        {
        "Software title": "PassMark Disk Checkup",
        "OS Available": ["Windows 7","Windows 8", "Windows 10"],
        "Category": "IT",
        "Checkbox":"Yes",
        "Generic link:":"https://www.passmark.com/downloads/diskcheckup.exe" ,
        "Software_name:":"diskcheckup.exe",
        "Software_type:":"exe",
        "Special_command_exists:":"Yes",
        "Special_Command:":"diskcheckup.exe /SILENT /NORESTART",
    },
    {
        "Software title": "SpeedFan",
        "OS Available": ["Windows 7","Windows 8", "Windows 10"],
        "Category": "PC Check",
        "Checkbox":"Yes",
        "Generic link:":"https://www.almico.com/instspeedfan452.exe" ,
        "Software_name:":"speedfan.exe",
        "Software_type:":"exe",
    },
    {
        "Software title": "FurMark",
        "OS Available": ["Windows 7","Windows 8", "Windows 10"],
        "Category": "PC Check",
        "Checkbox":"Yes",
        "Generic link:":"https://geeks3d.com/downloads/2019/FurMark_1.20.8.0_Setup.exe" ,
        "Software_name:":"FurMark.exe",
        "Software_type:":"exe",
        "Special_command_exists:":"Yes",
        "Special_Command:":"FurMark.exe /SILENT /NORESTART",
    },
    {
        "Software title": "Crystal Disk Info",
        "OS Available": ["Windows 7","Windows 8", "Windows 10"],
        "Category": "PC Check",
        "Checkbox":"Yes",
        "Generic link:":"https://free.nchc.org.tw/osdn//crystaldiskinfo/78836/CrystalDiskInfo9_0_1a.exe" ,
        "Software_name:":"CrystalDiskInfo.exe",
        "Software_type:":"exe",
        "Special_command_exists:":"Yes",
        "Special_Command:":"CrystalDiskInfo.exe /SILENT /NORESTART",
    },
]

